### ISSUE TITLE
Can't connect with USB Wi-Fi

### ISSUE THREAD

**Issue by nriley** [eofster/Telephone#246] opened 2016-07-02 14:33 UTC
I recently started using a USB Wi-Fi adapter as my Mac mini’s internal Wi-Fi sometimes becomes unreliable. Unfortunately, when I switch this adapter on and my internal adapter off, I am unable to connect with Telephone.

The error I get from Telephone is:

> Could not start SIP user agent.
> Please check your network connection and STUN server settings.

and from Console doesn't seem any more helpful:

```
7/2/16 10:31:47.858 AM Telephone[31281]: Error initializing PJSUA
7/2/16 10:31:47.951 AM Telephone[31281]: Could not start SIP user agent. Please check your network connection and STUN server settings.
```
I have no problem with other SIP clients over USB Wi-Fi, and have not noticed similar issues with other applications either.

**Comment by eofster** [comment] 2016-07-04 13:32
Could you please set the debug level by running this command in Terminal when Telephone is not launched:

```
defaults write com.tlphn.Telephone LogLevel -integer 4
```

and then reproduce the problem and attach (or send me) the log file located here?

```
/Users/username/Library/Containers/com.tlphn.Telephone/Data/Library/Application Support/com.tlphn.Telephone/Telephone.log
```

Please quit Telephone before sending the log file for the log file to be complete.

**Comment by nriley** [comment] 2016-07-04 21:18
Here you are. Thanks!

[broken.txt](https://github.com/eofster/Telephone/files/346834/broken.txt)

**Comment by eofster** [comment] 2016-07-05 07:38
The problem is in the DNS address, however I can’t tell the exact reason yet. Could you try to set the debug level and gather the log again? Please make sure that Telephone is NOT running when you enter a command in Terminal (the current log is not of debug level for some reason). Could you also either copy all DNS servers in the system or make the screenshot from here: System Preferences > Network > Your active network device > Advanced... > DNS?

**Comment by eofster** [comment] 2016-07-05 07:39
Alternatively, to get the list of current DNS servers you can run this command in Terminal:

```
cat /etc/resolv.conf
```

**Comment by eofster** [comment] 2016-07-05 10:20
I suspect, you have an IPv6 address there, and Telephone doesn’t currently support IPv6-only networks. The support is planned for the next release.

**Comment by nriley** [comment] 2016-07-05 11:51
I do have both IPv4 and IPv6 DNS addresses showing up.  Indeed, if I set "Configure IPv6" to "Link-local only" in System Preferences, Telephone will start successfully.  Thanks, I can use this workaround until the next release.

**Comment by nriley** [comment] 2016-07-05 12:09
I should mention that I did verify the log level was 4 and that I had quit Telephone.  If I delete the log level, I only get the single line about "invalid DNS nameserver address" in the log.

**Comment by eofster** [comment] 2016-07-05 12:14
Duplicate of #150.

**Closed by eofster** 2016-07-05 12:14 UTC

**Comment by eofster** [comment] 2016-07-05 12:17
About the log level – right, it was my fault. The log is perfectly normal for the level 4, I confused it because it was pretty short. :)
