### ISSUE TITLE
Automatic (re)connection

### ISSUE THREAD

**Issue by benrubson** [eofster/Telephone#117] opened 2014-12-16 16:01 UTC
Hello,

After my Mac went to sleep, all accounts are (and stay) offline.
I have to manually reconnect them.

In addition, if SIP port used is not the default one (registry server is for example "myserver.com:22222"), then accounts do not automatically connect when Telephone is started.

Could you please make (re)connection an automatic behavior ?

Thank you very much !

**Comment by robertoschwald** [comment] 2015-03-04 10:29
Duplicate of #79

**Comment by benrubson** [comment] 2015-05-25 06:47
Well, not really, I also talk here about non-default port.
I remember that Telephone used to connect automatically to the default port, but not to another.

**Comment by benrubson** [comment] 2015-05-31 12:23
As we do not have so many news from the developper, I tried to correct this issue myself.
So for those who have to courage to recompile Telephone to have their proper patched version, here is a (not so nice but working) workaround.

In Classes/Categories/AKNSString+Scanning.m :
make method ak_isIPAddress always return YES

**Comment by robertoschwald** [comment] 2016-01-15 08:06
@benrubson tried your workaround, but Telephone stays offline after wake from sleep.

**Comment by benrubson** [comment] 2016-01-15 08:28
Last version I patched is the following one : https://github.com/eofster/Telephone/tree/b311ee271b9aa14a9adfb65471029133bf100acb

And here is the modified method :
```
- (BOOL)ak_isIPAddress {

    //NSPredicate *IPAddressPredicate
    //    = [NSPredicate predicateWithFormat:@"SELF MATCHES "
    //       "'\\\\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\."
    //       "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\."
    //       "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\."
    //       "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\\\b'"];
    return YES;
    //return ([IPAddressPredicate evaluateWithObject:self]) ? YES : NO;
}
```

My Telephone is always automatically up and running online, even after wake from sleep, computer restart...

Perhaps you tried to patch a newer version, and as Alexei made a lot of changes last months, perhaps this patch is not working anymore against last versions of code ?

**Comment by robertoschwald** [comment] 2016-01-15 08:38
I added logs to AKNetworkReachability.AKReachabilityChanged, but it is never triggered after wakeup on El Capitan.

**Comment by benrubson** [comment] 2016-01-15 08:52
I'm also running El Capitan.
Try patching against the following tree ?
https://github.com/eofster/Telephone/tree/b311ee271b9aa14a9adfb65471029133bf100acb

**Comment by robertoschwald** [comment] 2016-01-15 09:01
Patching against master. Found out that AKNetworkReachabilityDidBecomeReachableNotification notification is not beeing triggered if the Domain in the account settings is a hostname.
When I changed that to the IP-Address of the PBX, it works! 

AKNetworkReachabilityDidBecomeReachableNotification is triggered after wakeup and Telephone reconnects.

**Comment by benrubson** [comment] 2016-01-15 09:30
I use hostname in the `Domain` field of my accounts, however as I do not use the common SIP port, I have something like :
`mysip.hostname.com:12345`

Try adding `:<port_number>` at the end of the hostname ?

**Closed** 2016-04-20 13:22 UTC
Labels: bug

**Comment by benrubson** [comment] 2016-04-20 13:26
👍

**Comment by robertoschwald** [comment] 2016-04-20 14:36
👍
